---
language: ruby
rvm:
- 1.9.2
- 1.9.3
- 1.8.7
script: bundle exec rake spec
after_success:
- git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
- .forge-releng/publish
env:
  global:
  - PUBLISHER_LOGIN=garethr
  - secure: ! 'l14aR3QH0tDhhASB9MtbiNu027kUIPPYYunN28fC7VRCtNWYuHZRhXjmfry8
      bIKAVsFlAcVX+rtiX5FNEy8p3Gl+KTfJxHOXxtJUIHdSjxp68P16bDY2mIH6
      ShQodk5GnM5ajPTCcAhay+nxLOg4S0afk5oW85V2WhyTvZoIauY='
  matrix:
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.18
  - PUPPET_VERSION=3.0.1
  - PUPPET_VERSION=3.1.0
